table mobile-cellular-subscriptions_no_code
	lineageTag: ac80203b-efb1-4937-858f-67b8fdf8c1ba

	column Entity
		dataType: string
		lineageTag: f556b15a-4c32-4413-9ba3-a288491b330a
		summarizeBy: none
		sourceColumn: Entity

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 49dead1e-c7b6-438b-87af-f5db93884f4b
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Mobile cellular subscriptions (per 100 people)'
		dataType: double
		lineageTag: 367b8595-843a-4621-81c8-de5d69e88e3c
		summarizeBy: sum
		sourceColumn: Mobile cellular subscriptions (per 100 people)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition mobile-cellular-subscriptions_no_code = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Nimbyx\OneDrive - Nimbyx Ltd\PBI10\mobile-cellular-subscriptions-per-100-people.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Entity", type text}, {"Code", type text}, {"Year", Int64.Type}, {"Mobile cellular subscriptions (per 100 people)", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Code] = "")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Year] >= 2010 and [Year] < 2022),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows1",{"Entity", "Year", "Mobile cellular subscriptions (per 100 people)"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

