table population_no_code
	lineageTag: fadf900d-7c9f-4c72-9ed0-54a6b289a67a

	column Entity
		dataType: string
		lineageTag: d2a7b90f-6312-4152-96e0-afe7d22ef246
		summarizeBy: none
		sourceColumn: Entity

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: c1ce2893-28b9-41bc-b34d-df6cd8a06785
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Population (historical)'
		dataType: int64
		formatString: 0
		lineageTag: ef47391e-2521-4e26-8777-75621cd109f8
		summarizeBy: sum
		sourceColumn: Population (historical)

		annotation SummarizationSetBy = Automatic

	column fixed_telephone_users
		dataType: double
		lineageTag: 54031c94-8c7d-4071-a3f7-6b81d27147b8
		summarizeBy: sum
		sourceColumn: fixed_telephone_users

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mobile_cellular_users
		dataType: double
		lineageTag: 6b41c885-387d-442f-b60b-88d320fc0748
		summarizeBy: sum
		sourceColumn: mobile_cellular_users

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column internet_users
		dataType: double
		lineageTag: 08db7922-a31a-4674-a447-134e5a089fad
		summarizeBy: sum
		sourceColumn: internet_users

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Code
		dataType: string
		lineageTag: c6f23e01-bd07-4075-8f96-6741fa3617f7
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	partition population_no_code = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\yskwak\Private\PBI10_Challenge\DataFiles\population.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Entity", type text}, {"Code", type text}, {"Year", Int64.Type}, {"Population (historical)", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Code] = "")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Entity", "Year", "Population (historical)"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Other Columns", each [Year] >= 2010 and [Year] < 2022),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows1", {"Entity", "Year"}, #"fixed-telephone-subscriptions_no_code", {"Entity", "Year"}, "fixed-telephone-subscriptions_no_code", JoinKind.LeftOuter),
				    #"Expanded fixed-telephone-subscriptions_no_code" = Table.ExpandTableColumn(#"Merged Queries", "fixed-telephone-subscriptions_no_code", {"Fixed telephone subscriptions (per 100 people)"}, {"fixed-telephone-subscriptions_no_code.Fixed telephone subscriptions (per 100 peo"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded fixed-telephone-subscriptions_no_code", {"Entity", "Year"}, #"mobile-cellular-subscriptions_no_code", {"Entity", "Year"}, "mobile-cellular-subscriptions_no_code", JoinKind.LeftOuter),
				    #"Expanded mobile-cellular-subscriptions_no_code" = Table.ExpandTableColumn(#"Merged Queries1", "mobile-cellular-subscriptions_no_code", {"Mobile cellular subscriptions (per 100 people)"}, {"mobile-cellular-subscriptions_no_code.Mobile cellular subscriptions (per 100 peo"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded mobile-cellular-subscriptions_no_code", {"Entity", "Year"}, #"number-of-internet-users_no_code", {"Entity", "Year"}, "number-of-internet-users_no_code", JoinKind.LeftOuter),
				    #"Expanded number-of-internet-users_no_code" = Table.ExpandTableColumn(#"Merged Queries2", "number-of-internet-users_no_code", {"Number of Internet users"}, {"number-of-internet-users_no_code.Number of Internet users"}),
				    #"Filtered Rows2" = Table.SelectRows(#"Expanded number-of-internet-users_no_code", each ([Entity] = "High-income countries" or [Entity] = "Low-income countries" or [Entity] = "Lower-middle-income countries" or [Entity] = "Upper-middle-income countries")),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows2","High-income countries","1.High-income",Replacer.ReplaceText,{"Entity"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Upper-middle-income countries","2.Upper-middle-income",Replacer.ReplaceText,{"Entity"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Lower-middle-income countries","3.Lower-middle-income",Replacer.ReplaceText,{"Entity"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Low-income countries","4.Low-income",Replacer.ReplaceText,{"Entity"}),
				    #"Added Code Column" = Table.AddColumn(#"Replaced Value3", "Code", each ""),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Code Column",{"Entity", "Code", "Year", "Population (historical)", "fixed-telephone-subscriptions_no_code.Fixed telephone subscriptions (per 100 peo", "mobile-cellular-subscriptions_no_code.Mobile cellular subscriptions (per 100 peo", "number-of-internet-users_no_code.Number of Internet users"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"number-of-internet-users_no_code.Number of Internet users", "internet_users"}, {"mobile-cellular-subscriptions_no_code.Mobile cellular subscriptions (per 100 peo", "mobile_cellular_users"}, {"fixed-telephone-subscriptions_no_code.Fixed telephone subscriptions (per 100 peo", "fixed_telephone_users"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

